[package]
name = "atomic-col"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["std"]
std = ["once_cell/std"]

[dependencies]
once_cell = { version = "1.13.0", features = ["alloc"], default-features = false }

[dev-dependencies]
rand = "0.8.5"